// Generated by typings
// Source: https://raw.githubusercontent.com/meteor-typings/angular2-compilers/master/main.d.ts
declare module "*.html" {
  const template: string;
  export default template;
}

declare module "*.less" {
  const template: string;
  export default template;
}

declare module "*.sass" {
  const template: string;
  export default template;
}

declare module "*.scss" {
  const template: string;
  export default template;
}
